name: OpenAPI.NET CI/CD Pipeline

on: [push, pull_request, workflow_dispatch]

jobs:
  ci:
    name: Continuous integration
    runs-on: ubuntu-latest
    outputs:
      latest-version: ${{ steps.get_semantic_version.outputs.version_num }}
    env:
      ARTIFACTS_FOLDER: ${{ github.workspace }}\Artifacts
      GITHUB_RUN_NUMBER: ${{ github.run_number }}
    steps:
      - name: Checkout repository
        id: checkout_repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      # - name: Setup .NET SDK
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: 5.0.x

      - name: Build projects
        id: build_projects
        shell: pwsh
        run: |
          $projectsArray = @(
            '.\src\Microsoft.OpenApi\Microsoft.OpenApi.csproj',
            '.\src\Microsoft.OpenApi.Readers\Microsoft.OpenApi.Readers.csproj',
            '.\src\Microsoft.OpenApi.Tool\Microsoft.OpenApi.Tool.csproj'
          )

          $projectsArray | ForEach-Object {
            dotnet build $PSItem `
            /p:Configuration=Release `
            /p:OutputPath=$env:ARTIFACTS_FOLDER
          }

          Push-Location Artifacts/
          New-Item NuGet -ItemType Directory
          Get-ChildItem *.nupkg -recurse | Move-Item -destination "NuGet"

      - name: Run unit tests
        id: run_unit_tests
        shell: pwsh
        run: |
          $testProjectsArray = @(
            '.\test\Microsoft.OpenApi.Tests\Microsoft.OpenApi.Tests.csproj',
            '.\test\Microsoft.OpenApi.Readers.Tests\Microsoft.OpenApi.Readers.Tests.csproj',
            '.\test\Microsoft.OpenApi.SmokeTests\Microsoft.OpenApi.SmokeTests.csproj'
          )

          $testProjectsArray | ForEach-Object {
            dotnet test $PSItem --configuration Release
          }

      - name: Upload NuGet packages as artifacts
        id: upload_nuget_pckgs
        uses: actions/upload-artifact@v1
        with:
          name: NuGet packages
          path: Artifacts\NuGet\

      # - name: Push NuGet packages to NuGet.org
      #   id: push_nuget_packages
      #   shell: pwsh
      #   run: |
      #     Push-Location Artifacts/NuGet/
      #     Get-ChildItem *.nupkg -recurse | ForEach-Object {
      #       nuget push $PSItem `
      #       -ApiKey $env:NUGET_API_KEY `
      #       -Source https://api.nuget.org/v3/index.json
      #     }
      #   env:
      #     NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

# Built with ❤ by [Pipeline Foundation](https://pipeline.foundation)